language: python
python:
  - "3.7.4"
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install .
# command to run tests
script: 
  - make test
  - py.test  --cov-report=xml --cov=bundle_notifications --cov=tests/
after_success:
  - codecov